name: AI Commit Messages
concurrency:
  group: ai-commit-${{ github.ref }}  # 1つずつ
  cancel-in-progress: true
on:
  push:
    branches: [ main ]
jobs:
  generate-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Wait & AI Commit
      uses: riccardolinares/openai-commit@v0.0.1
      with:
        openai-api-key: ${{ secrets.OPENAI_API_KEY }}
        model: gpt-4o-mini
